### ISSUE TITLE
테스트 실행 시 모든 이미지를 모킹하기

### ISSUE THREAD

**Issue by SihyeonHong** [fesi-05-01/frontend#112]
문제 상황: 
jest가 svg나 이미지 파일을 처리 못 하기 때문에 svg가 포함된 모든 테스트에서 fail이 뜹니다. 

해결하려면: 
테스트 시에는 모든 svg와 이미지 컴포넌트를 모킹해야 합니다. 
1. 각 테스트 코드에서 매번 이 컴포넌트에 포함된 모든 이미지 따로따로 모킹하기 
2. jest.config.ts 등 전역 설정으로 모든 이미지들을 대체하게 하기

두 번째 방법을 시도 중인데 잘 안 됩니다. 
성공하면 모두에게 해당하는 설정이니 PR 올리겠습니다.

**Comment by devyouth94** [comment]
굿굿
