### ISSUE TITLE
플로팅 바 취소하기랑 참여하기 버튼

### ISSUE THREAD

**Issue by SihyeonHong** [fesi-05-01/frontend#117]
조건문이 반대더라고요? 로그인 안 했는데 공유하기 뜨길래 이건 제가 그냥 고쳤고요 
취소하기랑 참여하기 버튼 기능 연결 필요

**Comment by yeyiwon** [comment]
앗 그러네요 조건문 반대로 적었네여 ㅋㅋㅋ
