### ISSUE TITLE
모임 만들기 수정 필요

### ISSUE THREAD

**Issue by cossgii** [fesi-05-01/frontend#125]
- 모임을 만들면 참여하기 안되고 0명인 상태로 시작되서 이 상황에 대해서 개선이 필요할 것 같습니다

![스크린샷 2024-12-13 141626](https://github.com/user-attachments/assets/71b0a0dc-c625-404a-9963-5493a667b703)

**Comment by devyouth94** [comment]
1. 모임 만들기 api 요청을 한다.
2. 요청이 성공하면 자동으로 현재 로그인 된 사용자의 토큰으로 모임 참여하기 api를 요청한다.
