### ISSUE TITLE
끝나지 않은 시간대 문제?

### ISSUE THREAD

**Issue by SihyeonHong** [fesi-05-01/frontend#132]
12월 17일 오전 9시로 모임 생성했는데 카드에 12월 17일 18시로 뜨네요 

+) 날짜 필터링 시에도 달력에서 12월 21일 선택했는데 22일 0시 데이터가 뜬다거나

**Comment by devyouth94** [comment]
넘길때랑 받아올때 서버에서 받아온 데이터 자체는 오전9시인가요??

**Comment by SihyeonHong** [comment]
> 넘길때랑 받아올때 서버에서 받아온 데이터 자체는 오전9시인가요??

화면만 보고 확인 안 해봤어요 중간발표 이후에 고치려고요
