### ISSUE TITLE
사진 렌더링 관련

### ISSUE THREAD

**Issue by devyouth94** [fesi-05-01/frontend#136]
<img width="57" alt="image" src="https://github.com/user-attachments/assets/991c72ac-48b4-43ac-86cc-e858820e1bf1" />

<img width="513" alt="image" src="https://github.com/user-attachments/assets/be30c828-6b8f-404d-a453-03b3caf253e1" />

사진 UI 렌더링 하실때 object-cover css 추가하는게 좋을듯 싶습니다.
세로로 긴 사진들은 전부 찌그러집니당~~

**Comment by SihyeonHong** [comment]
저는 찌그러지는 게 낫다고 생각했습니다 모임마다 카드 사이즈나 형태가 달라지면 통일성이 없어보이고 css 컨트롤하기가 더 어렵다고 판단했습니다.

**Comment by devyouth94** [comment]
> 저는 찌그러지는 게 낫다고 생각했습니다 모임마다 카드 사이즈나 형태가 달라지면 통일성이 없어보이고 css 컨트롤하기가 더 어렵다고 판단했습니다.

https://tailwindcss.com/docs/object-fit
그냥 사진 비율 유지한채로 카드 안에 꽉차게 넣으면 되는거라서 어렵진 않을거에여
그리고 사진은 어느 상황에서든 찌그러지면 안됩니다

**Comment by SihyeonHong** [comment]
object-cover 언급하신 건 사진이 잘리게 넣으라는 말씀이시죠?

**Comment by devyouth94** [comment]
> object-cover 언급하신 건 사진이 잘리게 넣으라는 말씀이시죠?

네에 overflow-hidden 개념으로 생각하시면 됩니다
