### ISSUE TITLE
텍스트 컬러 및 두께 기본 설정 관련

### ISSUE THREAD

**Issue by devyouth94** [fesi-05-01/frontend#75]
텍스트 사이즈는 기준으로 잡을만한게 크게 없어보이고

컬러는 text-secondary-900과 800이 기본 컬러인것 같아요. 두개가 거의 차이가 없는데 혼동되서 쓰이고 있긴 한데,,, 어떤 기준으로 차이점이 있는지는 모르겠습니다.

두께는 medium이 기본 두께인것 같아요.

1. 컬러와 두께를 기본 값을 지정할지 말지
2. 지정한다면 컬러는 어떤값으로 기본값을 정할지
3. 900과 800은 한 컬러로 통일할지

의견 주세요~~😖

**Comment by SihyeonHong** [comment]
전 기본값 있으면 편할 것 같고 900 800 통일하는 것도 좋아요 
800 900 중에 고르라고 한다면... 그건 진짜 둘이 같이 두고 봐도 차이를 모르겠어요....

**Comment by yeyiwon** [comment]
별 차이는 못 느끼지만 이왕 기본 값 정할 거면 덜 쨍한 800 !
