### ISSUE TITLE
사진 올림 성공 이슈 

### ISSUE THREAD

**Issue by yeyiwon** [fesi-05-01/frontend#77]
어케어케 해서 이미지 파일 업로드를 성공했습니다
제꺼 머지 하기 전에 사진 올려보고 띄워보려는데 이런 이슈나온다면 참고하시면 됩니당 

근데 올리고 프로필 사진 보려하니 
<img width="1080" alt="스크린샷 2024-12-06 오전 12 02 15" src="https://github.com/user-attachments/assets/7f40bfe4-e53b-4830-b848-c69c05fd5822">

스프린트 ,,아마존,, 이런 에러가 떴습니다 이 새벽에 이미지 업로드 성공해서 행복했는데 

저희 api 서버에서 아무나 안된다 한 건지 

<img width="830" alt="스크린샷 2024-12-06 오전 12 03 43" src="https://github.com/user-attachments/assets/184bdb2a-e397-4deb-8ef3-e8b673054863">

```
  images: {
    domains: ['sprint-fe-project.s3.ap-northeast-2.amazonaws.com'],
  },

``` 

추가해주면 된다고 합니다

<img width="1081" alt="스크린샷 2024-12-06 오전 12 06 33" src="https://github.com/user-attachments/assets/48966dca-aea2-4ecd-bcb2-184334cca04c">

<img width="1081" alt="스크린샷 2024-12-06 오전 12 11 54" src="https://github.com/user-attachments/assets/15d6ece3-898c-42b0-a5de-af20c54b6adc">

**Comment by devyouth94** [comment]
좋습니다~~👍
