### ISSUE TITLE
notfound 페이지랑 로딩 컴포넌트 하나 만들면 좋을 것 같습니당 

### ISSUE THREAD

**Issue by yeyiwon** [fesi-05-01/frontend#98]
<img width="722" alt="스크린샷 2024-12-10 오후 10 11 05" src="https://github.com/user-attachments/assets/d38fa01e-614a-4881-b1b1-0e0b6c3a5fde">

그냥 가볍게 텍스트 정도로만 ? 처리해두기만 하는 건 어떨까용 

loading 파일이랑 notfound 파일만 app 에 놓기만 해도 되니까 🙌🏻 사진은 같이 만들어 놓고 찍은 겁니당

**Comment by devyouth94** [comment]
캬~~~ 좋습니다 👍 👍
